/**
 * Type definitions for conventions, named styles, and format resolution.
 */

// ── Border weight ────────────────────────────────────────────────────

export type BorderWeight = "thin" | "medium" | "thick" | "none";

// ── Number format presets ────────────────────────────────────────────

export type NumberPreset = "number" | "integer" | "currency" | "percent" | "ratio" | "text";

// ── Format-builder conventions ───────────────────────────────────────

export type NegativeStyle = "parens" | "minus";
export type ZeroStyle = "dash" | "single-dash" | "zero" | "blank";

export interface NumberFormatConventions {
  negativeStyle: NegativeStyle;
  zeroStyle: ZeroStyle;
  thousandsSeparator: boolean;
  accountingPadding: boolean;
}

export interface FormatBuilderParams {
  dp?: number;
  negativeStyle?: NegativeStyle;
  zeroStyle?: ZeroStyle;
  thousandsSeparator?: boolean;
  currencySymbol?: string;
}

export interface StoredFormatPreset {
  /** Actual Excel format string used by format resolution. */
  format: string;
  /** Optional metadata if generated by quick toggles/builder. */
  builderParams?: FormatBuilderParams;
}

export interface StoredCustomPreset extends StoredFormatPreset {
  description?: string;
}

// ── Visual conventions ───────────────────────────────────────────────

export interface StoredVisualDefaults {
  fontName?: string;
  fontSize?: number;
}

export interface StoredColorConventions {
  /** Font color for hardcoded values. */
  hardcodedValueColor?: string;
  /** Font color for cross-sheet links. */
  crossSheetLinkColor?: string;
}

export interface StoredHeaderStyle {
  fillColor?: string;
  fontColor?: string;
  bold?: boolean;
  wrapText?: boolean;
}

export interface StoredConventions {
  /** Built-in preset format overrides. */
  presetFormats?: Partial<Record<NumberPreset, StoredFormatPreset>>;
  /** User-defined custom presets by name. */
  customPresets?: Record<string, StoredCustomPreset>;
  /** Visual defaults (font name/size). */
  visualDefaults?: StoredVisualDefaults;
  /** Font color conventions. */
  colorConventions?: StoredColorConventions;
  /** Header style overrides. */
  headerStyle?: StoredHeaderStyle;
}

export interface ResolvedVisualDefaults {
  fontName: string;
  fontSize: number;
}

export interface ResolvedColorConventions {
  hardcodedValueColor: string;
  crossSheetLinkColor: string;
}

export interface ResolvedHeaderStyle {
  fillColor: string;
  fontColor: string;
  bold: boolean;
  wrapText: boolean;
}

export interface ResolvedConventions {
  presetFormats: Record<NumberPreset, StoredFormatPreset>;
  customPresets: Record<string, StoredCustomPreset>;
  visualDefaults: ResolvedVisualDefaults;
  colorConventions: ResolvedColorConventions;
  headerStyle: ResolvedHeaderStyle;
}

// ── Cell style properties ────────────────────────────────────────────

export interface CellStyle {
  // Number format
  numberFormat?: string;
  numberFormatDp?: number;
  currencySymbol?: string;

  // Font
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  fontColor?: string;
  fontSize?: number;
  fontName?: string;

  // Fill
  fillColor?: string;

  // Borders (individual edges)
  borderTop?: BorderWeight;
  borderBottom?: BorderWeight;
  borderLeft?: BorderWeight;
  borderRight?: BorderWeight;

  // Alignment
  horizontalAlignment?: "Left" | "Center" | "Right" | "General";
  verticalAlignment?: "Top" | "Center" | "Bottom";
  wrapText?: boolean;
}

export interface NamedStyle {
  name: string;
  description: string;
  properties: CellStyle;
  builtIn: true;
}

export interface ResolvedCellStyle {
  properties: CellStyle;
  excelNumberFormat?: string;
  warnings: string[];
}
